'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {apiRequest} from '@/lib/api-client';
import {Panel,PageIntro,Stat} from '@/components/page-ui';
type TableRow=Record<string,string|number>;type Reports={generatedAt?:string;orderCount?:number;profit?:Record<string,number>;accounts?:Record<string,number>;flooring?:Record<string,number>;service?:Record<string,number>;delivery?:Record<string,number>;assembly?:Record<string,number>;salesByChannel?:TableRow[];salesByDay?:TableRow[];salesByProduct?:TableRow[];salesBySupplier?:TableRow[]};
const pounds=(value:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((value??0)/100);
function Table({title,rows,columns}:{title:string;rows:TableRow[];columns:string[]}){return <Panel title={title}><div className="table-wrap"><table><thead><tr>{columns.map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(col=><td key={col}>{typeof row[col]==='number'&&col.toLowerCase().includes('pence')?pounds(row[col]):String(row[col]??'—')}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<p style={{padding:16}}>No report data yet.</p>}</Panel>}
export function ReportsWorkspace(){const [data,setData]=useState<Reports>({});const [error,setError]=useState('');useEffect(()=>{apiRequest<Reports>('/api/reports').then(setData).catch(e=>setError((e as Error).message));},[]);
return <div className="page"><PageIntro eyebrow="AH INTERIORS / INSIGHTS" title="Reports" description="Live summaries from shared CRM records. Profit summaries use verified supplier costs recorded in each order." action={<Link className="btn" href="/">Dashboard</Link>}/>{error&&<p role="alert">{error}</p>}
{data.profit&&<><h2>Profit</h2><div className="metric-grid"><Stat label="Gross profit" value={pounds(data.profit.grossPence)} note="Verified supplier costs recorded"/><Stat label="Contribution" value={pounds(data.profit.contributionPence)} note="Only tracked costs are included"/><Stat label="Average margin" value={(data.profit.averageMarginBps/100).toFixed(1)+'%'} note={data.profit.costCoverage+' orders with cost coverage'}/><Stat label="Below minimum" value={String(data.profit.belowMinimum)} note="Needs margin review"/></div></>}
{data.accounts&&<div className="metric-grid"><Stat label="Invoiced" value={pounds(data.accounts.invoiced)} note="Issued invoices"/><Stat label="Paid" value={pounds(data.accounts.paid)} note="Recorded payments"/><Stat label="Outstanding" value={pounds(data.accounts.outstanding)} note="Current invoice balances"/><Stat label="Overdue" value={pounds(data.accounts.overdue)} note="Past due date"/></div>}
{data.flooring&&<div className="metric-grid"><Stat label="Flooring leads" value={String(data.flooring.leads)} note="All accessible leads"/><Stat label="Won" value={String(data.flooring.won)} note="Converted leads"/><Stat label="Quotes" value={String(data.flooring.quotes)} note="Open quotes"/><Stat label="Lost" value={String(data.flooring.lost)} note="Closed lost"/></div>}
{data.service&&<div className="metric-grid"><Stat label="Open cases" value={String(data.service.open)} note="Customer service"/><Stat label="Overdue cases" value={String(data.service.overdue)} note="Chase date passed"/></div>}
{data.delivery&&<div className="metric-grid"><Stat label="Delivery jobs" value={String(data.delivery.total)} note="Accessible jobs"/><Stat label="Failed" value={String(data.delivery.failed)} note="Requires follow-up"/><Stat label="Rescheduled" value={String(data.delivery.rescheduled)} note="Rebooking"/><Stat label="Completed" value={String(data.delivery.completed)} note="Delivered"/></div>}
{data.assembly&&<div className="metric-grid"><Stat label="Assembly jobs" value={String(data.assembly.total)} note="Accessible jobs"/><Stat label="Issues" value={String(data.assembly.issues)} note="Needs attention"/><Stat label="Completed" value={String(data.assembly.completed)} note="Customer sign-off"/></div>}
<Table title="Sales by channel" rows={data.salesByChannel??[]} columns={['channel','orders','salesPence']}/>{data.salesByDay&&<Table title="Sales by day" rows={data.salesByDay} columns={['date','salesPence']}/ >}{data.salesByProduct&&<Table title="Sales by product" rows={data.salesByProduct} columns={['product','units','revenuePence']}/ >}{data.salesBySupplier&&<Table title="Sales by supplier" rows={data.salesBySupplier} columns={['supplier','orders','salesPence']}/ >}</div>}
