export type BusinessModule='deliveries'|'assembly-jobs'|'flooring'|'service-cases'|'tasks'|'expenses'|'approvals';
export type BusinessField={key:string;label:string;type:'text'|'textarea'|'date'|'datetime'|'number'|'money'|'boolean'|'select'|'rooms'|'quote';required?:boolean;options?:string[]};
export type ModuleDefinition={title:string;singular:string;prefix:string;statuses:string[];readRoles:string[];writeRoles:string[];customer?:boolean;order?:boolean;fields:BusinessField[]};
const operations=['Management','Team Lead','Customer Service & Sales'];const management=['Management'];
const field=(key:string,label:string,type:BusinessField['type']='text',required=false):BusinessField=>({key,label,type,required});
export const businessModules:Record<BusinessModule,ModuleDefinition>={
 'deliveries':{title:'Delivery management',singular:'delivery job',prefix:'DEL',statuses:['Awaiting Stock','Ready to Book','Customer Contact Required','Booked','Confirmed','Out for Delivery','Delivered','Failed','Rescheduled','Completed'],readRoles:[...operations,'Warehouse','Delivery'],writeRoles:operations,customer:true,order:true,fields:[field('groupId','Fulfilment group','text',true),field('address','Delivery address','textarea',true),field('postcode','Postcode','text',true),field('phone','Contact phone'),field('packs','Number of packs','number'),field('scheduledDate','Delivery date','date'),field('timeSlot','Time slot'),field('team','Delivery team'),field('vehicle','Vehicle'),field('courier','Courier'),field('assemblyRequired','Assembly required','boolean'),field('customerConfirmed','Customer confirmed','boolean'),field('proof','Proof of delivery / signature reference'),field('failedReason','Failed delivery reason'),field('rescheduledDate','Rescheduled date','date'),field('deliveryCostPence','Actual delivery cost (£)','money'),field('notes','Notes','textarea')]},
 'assembly-jobs':{title:'Assembly jobs',singular:'assembly job',prefix:'ASM',statuses:['Awaiting Booking','Booked','Confirmed','In Progress','Completed','Issue Reported','Rescheduled','Cancelled'],readRoles:[...operations,'Installer'],writeRoles:operations,customer:true,order:true,fields:[field('groupId','Fulfilment group','text',true),field('deliveryId','Linked delivery ID'),field('address','Assembly address','textarea',true),field('scheduledDate','Scheduled date','date'),field('timeSlot','Time slot'),field('team','Installer team'),field('feePence','Assembly fee (£)','money'),field('extraChargesPence','Extra charges (£)','money'),field('customerSignoff','Customer sign-off reference'),field('problem','Problem reported','textarea'),field('notes','Notes','textarea')]},
 'flooring':{title:'Flooring CRM',singular:'flooring lead',prefix:'FLR',statuses:['Lead','Measure Booked','Measure Completed','Quote','Follow-up','Won','Lost','Materials Ordered','Fitting Booked','Installation','Completed'],readRoles:operations,writeRoles:operations,customer:true,fields:[field('leadSource','Lead source'),{key:'productType',label:'Product type',type:'select',options:['Carpet','Laminate','LVT','Vinyl','Wood','Other']},field('room','Room'),field('approxSqm','Approximate sqm','number'),field('budgetPence','Budget (£)','money'),field('branch','Branch'),field('measureDate','Measure date','date'),field('measureTime','Measure time'),field('surveyor','Surveyor'),field('samples','Samples required'),field('measureNotes','Measure notes','textarea'),field('rooms','Room measurements','rooms'),field('quote','Quote','quote'),field('nextChaseDate','Next follow-up','date'),field('outcome','Follow-up outcome'),{key:'lostReason',label:'Lost reason',type:'select',options:['','Price','Competitor','No response','Changed mind','Delayed','Product unavailable','Other']},field('fittingDate','Fitting date','date'),field('notes','Notes','textarea')]},
 'service-cases':{title:'Customer service',singular:'customer service case',prefix:'CS',statuses:['New','Investigating','Awaiting Customer','Awaiting Supplier','Replacement Ordered','Replacement In Transit','Ready to Resolve','Resolved','Closed'],readRoles:operations,writeRoles:operations,customer:true,fields:[{key:'caseType',label:'Case type',type:'select',required:true,options:['Damage','Missing Pack','Missing Part','Wrong Product','Delivery Issue','Assembly Issue','Supplier Issue','Return','Refund','Complaint','Other']},{key:'priority',label:'Priority',type:'select',options:['Low','Normal','High','Urgent']},field('reportedDate','Date reported','date',true),field('description','Description','textarea',true),field('supplierContacted','Supplier contacted','boolean'),field('supplierResponse','Supplier response','textarea'),field('replacementRequired','Replacement required','boolean'),field('replacementReference','Replacement order/reference'),field('expectedReplacementDate','Expected replacement date','date'),field('customerLastUpdated','Customer last updated','date'),field('nextChaseDate','Next chase date','date'),field('resolution','Resolution','textarea'),field('resolutionDate','Resolution date','date')]},
 'tasks':{title:'Tasks & follow-ups',singular:'task',prefix:'TASK',statuses:['Open','In Progress','Completed','Cancelled'],readRoles:[...operations,'Accounts','Warehouse','Delivery','Installer','Shopify Store Manager'],writeRoles:[...operations,'Accounts','Warehouse','Shopify Store Manager'],fields:[field('description','Description','textarea'),{key:'priority',label:'Priority',type:'select',options:['Low','Normal','High','Urgent']},field('dueDate','Due date','date',true),field('reminderDate','Reminder','datetime'),{key:'linkedType',label:'Linked record type',type:'select',options:['','customer','order','supplier','purchase-order','supplier-order','delivery','assembly','flooring','service-case']},field('linkedId','Linked record ID')]},
 'expenses':{title:'Business expenses',singular:'expense',prefix:'EXP',statuses:['Draft','Submitted','Approved','Rejected','Paid'],readRoles:['Management','Team Lead','Accounts'],writeRoles:['Management','Team Lead','Accounts'],fields:[field('expenseDate','Expense date','date',true),field('category','Category','text',true),field('payee','Supplier / payee','text',true),field('description','Description','textarea',true),field('amountPence','Net amount (£)','money',true),field('vatPence','VAT (£)','money'),field('paymentMethod','Payment method'),field('branch','Branch'),field('department','Department'),field('notes','Notes','textarea')]},
 'approvals':{title:'Management approvals',singular:'approval request',prefix:'APR',statuses:['Requested','Approved','Rejected'],readRoles:[...operations,'Accounts','Warehouse','Shopify Store Manager'],writeRoles:[...operations,'Accounts','Warehouse','Shopify Store Manager'],fields:[{key:'approvalType',label:'Approval type',type:'select',required:true,options:['Low margin','Large discount','Refund','Stock adjustment','High-value expense','Order cancellation']},field('reason','Reason','textarea',true),{key:'linkedType',label:'Related record type',type:'select',options:['order','invoice','product','stock-movement','expense','purchase-order']},field('linkedId','Related record ID','text',true),field('amountPence','Approved amount (£)','money'),field('notes','Decision notes','textarea')]},
};
export function canUseModule(role:string,module:BusinessModule,write=false){const definition=businessModules[module];return (write?definition.writeRoles:definition.readRoles).includes(role);}
export function blankDetails(module:BusinessModule):Record<string,unknown>{return Object.fromEntries(businessModules[module].fields.map(v=>[v.key,v.type==='boolean'?false:v.type==='number'||v.type==='money'?0:v.type==='rooms'?[]:v.type==='quote'?{lines:[],underlayPence:0,accessoriesPence:0,fittingPence:0,removalPence:0,deliveryPence:0,discountPence:0,costPence:0}:v.type==='select'?v.options?.[0]??'':'']));}
