// Existing synthetic inbox content, preserved from the original Communications preview.
export const sampleMail = [
  {
    id: 'rauch',
    from: 'Rauch',
    initials: 'R',
    subject: 'Order confirmation — price to review',
    preview: 'Confirmed cost £1,390 for Lucy Turner.',
    date: 'Today, 10:32',
    status: 'Needs review',
    tone: 'red' as const,
    order: '10004812',
    body: 'Hello AH Interiors,\n\nPlease find attached our confirmation for Lucy Turner’s Imperial wardrobe order. The confirmed cost is £1,390.\n\nPlease check the product specification and price, and let us know if you need any amendments before production.\n\nKind regards,\nRauch Order Support',
    file: 'Rauch-Confirmation-8273662.pdf',
    note: 'Expected cost £1,040 · Confirmed £1,390 · Difference £350',
    draft:
      'Hello,\n\nThank you for the confirmation. Our expected cost for order #10004812 is £1,040, but the confirmation shows £1,390. Please clarify the £350 difference and confirm the product specification before we approve the change.\n\nKind regards,\nAH Interiors',
  },
  {
    id: 'flatpack',
    from: 'Flatpack Assembly',
    initials: 'FA',
    subject: 'Alternative assembly date — Nadia Khan',
    preview: '18 September is unavailable. Can we offer 22 September?',
    date: 'Today, 09:55',
    status: 'Needs review',
    tone: 'gold' as const,
    order: '10004786',
    body: 'Hello,\n\nUnfortunately our team cannot attend Nadia Khan’s requested assembly date of 18 September. We can offer 22 September instead, subject to the wardrobe being delivered.\n\nPlease confirm the delivery date with the supplier before we reserve an appointment.\n\nThanks,\nFlatpack Assembly',
    file: '',
    note: 'Supplier delivery is Week 42. Neither September date should be booked before the delivery is checked.',
    draft:
      'Hello,\n\nThank you for the alternative. The current supplier estimate is Week 42, so we need to verify delivery before choosing an assembly date. Please keep the booking unconfirmed for now.\n\nKind regards,\nAH Interiors',
  },
  {
    id: 'sarah',
    from: 'Sarah Jones',
    initials: 'SJ',
    subject: 'A quick question about delivery',
    preview: 'Could you let me know when my mattress will arrive?',
    date: 'Today, 09:31',
    status: 'Customer query',
    tone: 'blue' as const,
    order: '10004822',
    body: 'Hi,\n\nI placed an order for the Luxury pocket mattress this morning. Could you let me know the expected delivery date when you have it?\n\nMy order number is 10004822.\n\nThank you,\nSarah',
    file: '',
    note: 'The order is awaiting purchasing review. No supplier delivery date is confirmed.',
    draft:
      'Hello Sarah,\n\nThank you for your order. We have received your order #10004822 and it is awaiting our purchasing review. We will update you as soon as the supplier confirms an estimated delivery date.\n\nKind regards,\nAH Interiors',
  },
  {
    id: 'hypnos',
    from: 'Hypnos',
    initials: 'H',
    subject: 'We have received your enquiry',
    preview: 'Reference HYP-88314 — confirmation to follow.',
    date: 'Yesterday, 16:20',
    status: 'Awaiting reply',
    tone: 'gold' as const,
    order: '10004798',
    body: 'Hello,\n\nYour enquiry about PO-2026-002829 has been logged under reference HYP-88314. Our order team will respond with the confirmed cost and delivery estimate.\n\nThis acknowledgement is not an order confirmation.\n\nRegards,\nHypnos Customer Service',
    file: '',
    note: 'Acknowledgement received. A verified order confirmation is still overdue.',
    draft:
      'Hello,\n\nFollowing up on reference HYP-88314 for PO-2026-002829, Daniel Wilson. Please send the confirmed cost and estimated delivery week so we can update our customer.\n\nKind regards,\nAH Interiors',
  },
  {
    id: 'john',
    from: 'John Smith',
    initials: 'JS',
    subject: 'Assembly for my wardrobe',
    preview: 'Will your team contact me to arrange assembly?',
    date: 'Yesterday, 15:48',
    status: 'Customer query',
    tone: 'blue' as const,
    order: '10004821',
    body: 'Hello,\n\nI have included assembly with my wardrobe order. Will the assembly team get in touch separately, or do I need to book a date with you?\n\nThanks,\nJohn',
    file: '',
    note: 'Assembly is included. A date will be arranged after the supplier delivery estimate is confirmed.',
    draft:
      'Hello John,\n\nAssembly is included in your order. Once the supplier confirms the delivery estimate, we will contact you to coordinate a suitable assembly date. There is no confirmed appointment yet.\n\nKind regards,\nAH Interiors',
  },
];
