import {updateOrderProgress} from './order-progress';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {eq,and,sql} from 'drizzle-orm';
import {database} from '../db';
import {purchaseOrders,purchaseItems,supplierOrders,suppliers,products,customers,orders,users,auditLogs,settings} from '../db/schema';
import {authorize,AppError,type Staff} from '../permissions';
import {purchaseStatuses,supplierStatuses,canTransition,supplierFlags} from '../../lib/supplier-workflow';
const id=z.string().min(1).max(128);const optionalId=z.union([id,z.literal('')]).optional();const date=z.iso.date();const optionalDate=z.union([date,z.literal('')]);const text=z.string().trim().max(10000);
export const purchaseInput=z.object({version:z.number().int().positive().optional(),supplierId:id,orderId:optionalId,customerId:optionalId,date,expectedDate:optionalDate,currency:z.enum(['GBP','EUR','USD']),accountReference:text.max(200),notes:text,items:z.array(z.object({productId:id,description:text.min(1).max(1000),quantity:z.number().int().positive().max(10000),unitCostPence:z.number().int().min(0).max(1000000000),customerId:optionalId}).strict()).min(1).max(200)}).strict();
export const trackingInput=z.object({version:z.number().int().positive().optional(),purchaseOrderId:id,ownerId:id,details:z.object({supplierOrderNumber:text.max(200),confirmationNumber:text.max(200),orderedDate:optionalDate,confirmationDate:optionalDate,expectedArrival:optionalDate,collectionRequired:z.boolean(),collectionCompany:text.max(200),collectionReference:text.max(200),collectionDate:optionalDate,lastContacted:optionalDate,nextChaseDate:optionalDate,deliveryBooked:z.boolean(),notes:text}).strict()}).strict();
export async function listPurchases(staff:Staff){authorize(staff,'approvals.write');const db=database();const rows=await db.select().from(purchaseOrders).orderBy(purchaseOrders.createdAt);const items=await db.select().from(purchaseItems);return rows.map(row=>({...row,items:items.filter(v=>v.purchaseOrderId===row.id&&v.active),totalPence:items.filter(v=>v.purchaseOrderId===row.id).reduce((sum,v)=>sum+v.quantity*v.unitCostPence,0)}));}
export async function savePurchase(staff:Staff,input:unknown,idValue?:string){authorize(staff,'approvals.write');const {version,items,...data}=purchaseInput.parse(input);const id=idValue??randomUUID();return database().transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(10204)`);
 const [supplier]=await tx.select().from(suppliers).where(eq(suppliers.id,data.supplierId));if(!supplier?.active)throw new AppError(422,'SUPPLIER_REQUIRED','Select an active supplier.');
 if(data.customerId&&!(await tx.select().from(customers).where(eq(customers.id,data.customerId))).length)throw new AppError(422,'CUSTOMER_REQUIRED','Customer not found.');
 if(data.orderId){const [order]=await tx.select().from(orders).where(eq(orders.id,data.orderId));if(!order||data.customerId&&order.customerId!==data.customerId)throw new AppError(422,'ORDER_REQUIRED','Order and customer must match.');}
 const [prior]=await tx.select().from(purchaseOrders).where(eq(purchaseOrders.id,id)).for('update');if(idValue&&!prior)throw new AppError(404,'NOT_FOUND','Purchase order not found.');
 if(prior&&(prior.status!=='Draft'||version!==prior.version))throw new AppError(409,'LOCKED','Only the current draft can be edited.');
 for(const item of items){const [product]=await tx.select().from(products).where(and(eq(products.id,item.productId),eq(products.supplierId,data.supplierId)));if(!product)throw new AppError(422,'PRODUCT_SUPPLIER','Purchase items must belong to the selected supplier.');if(item.customerId&&!(await tx.select().from(customers).where(eq(customers.id,item.customerId))).length)throw new AppError(422,'CUSTOMER_REQUIRED','Allocated customer not found.');}
 const [record]=await tx.insert(purchaseOrders).values({...data,orderId:data.orderId||null,customerId:data.customerId||null,id,number:prior?.number??'PO-'+new Date().getFullYear()+'-'+id.slice(0,8).toUpperCase(),buyerId:staff.id}).onConflictDoUpdate({target:purchaseOrders.id,set:{...data,orderId:data.orderId||null,customerId:data.customerId||null,version:(prior?.version??0)+1,updatedAt:new Date()}}).returning();
 if(prior)await tx.update(purchaseItems).set({active:false}).where(eq(purchaseItems.purchaseOrderId,id));
 for(const item of items){const [product]=await tx.select().from(products).where(eq(products.id,item.productId));await tx.insert(purchaseItems).values({...item,id:randomUUID(),purchaseOrderId:id,supplierSku:product.supplierSku,customerId:item.customerId||null});}
 await tx.insert(auditLogs).values({userId:staff.id,entity:'purchase-order',entityId:id,action:prior?'draft-updated':'created',before:prior,after:{...record,items}});return record;
});}
export async function transitionPurchase(staff:Staff,id:string,input:unknown){authorize(staff,'approvals.write');const data=z.object({version:z.number().int().positive(),status:z.enum(purchaseStatuses)}).strict().parse(input);return database().transaction(async tx=>{
 const [prior]=await tx.select().from(purchaseOrders).where(eq(purchaseOrders.id,id)).for('update');if(!prior)throw new AppError(404,'NOT_FOUND','Purchase order not found.');
 if(prior.version!==data.version)throw new AppError(409,'VERSION_CONFLICT','Purchase order changed. Reload before updating.');
 if(!canTransition(purchaseStatuses,prior.status,data.status))throw new AppError(422,'TRANSITION','Complete the preceding purchase stage first.');
 if(['Partially Received','Received'].includes(data.status))throw new AppError(422,'RECEIVING_REQUIRED','Use goods receiving to update received quantities and stock.');
 const [record]=await tx.update(purchaseOrders).set({status:data.status,version:prior.version+1,updatedAt:new Date()}).where(eq(purchaseOrders.id,id)).returning();
 await tx.insert(auditLogs).values({userId:staff.id,entity:'purchase-order',entityId:id,action:'status-changed',before:{status:prior.status},after:{status:data.status}});return record;
});}
export async function listSupplierOrders(staff:Staff){authorize(staff,'approvals.write');const db=database();const [rules]=await db.select().from(settings).where(eq(settings.key,'business'));if(!rules)throw new AppError(503,'SETTINGS_REQUIRED','Initialize business settings first.');const rows=await db.select().from(supplierOrders).orderBy(supplierOrders.createdAt);return rows.map(row=>({...row,flags:supplierFlags(row,(rules.value as {supplierConfirmationDays:number}).supplierConfirmationDays)}));}
export async function saveSupplierOrder(staff:Staff,input:unknown,idValue?:string){authorize(staff,'approvals.write');const {version,...data}=trackingInput.parse(input);const id=idValue??randomUUID();return database().transaction(async tx=>{
 const [purchase]=await tx.select().from(purchaseOrders).where(eq(purchaseOrders.id,data.purchaseOrderId));if(!purchase)throw new AppError(422,'PURCHASE_REQUIRED','Select an existing purchase order.');
 const [owner]=await tx.select().from(users).where(and(eq(users.id,data.ownerId),eq(users.active,true)));if(!owner)throw new AppError(422,'OWNER_REQUIRED','Select active staff.');
 const [prior]=await tx.select().from(supplierOrders).where(eq(supplierOrders.id,id)).for('update');if(idValue&&!prior)throw new AppError(404,'NOT_FOUND','Supplier order not found.');if(prior&&prior.version!==version)throw new AppError(409,'VERSION_CONFLICT','Supplier order changed. Reload first.');if(prior&&prior.purchaseOrderId!==data.purchaseOrderId)throw new AppError(422,'LOCKED_LINK','An existing supplier order cannot change purchase order.');
 const [record]=await tx.insert(supplierOrders).values({...data,id,number:'SO-'+id.slice(0,8).toUpperCase(),supplierId:purchase.supplierId,orderId:purchase.orderId,customerId:purchase.customerId}).onConflictDoUpdate({target:supplierOrders.id,set:{details:data.details,ownerId:data.ownerId,version:(prior?.version??0)+1,updatedAt:new Date()}}).returning();await tx.insert(auditLogs).values({userId:staff.id,entity:'supplier-order',entityId:id,action:prior?'updated':'created',before:prior,after:record});return record;
});}
export async function transitionSupplierOrder(staff:Staff,id:string,input:unknown){authorize(staff,'approvals.write');const data=z.object({version:z.number().int().positive(),status:z.enum(supplierStatuses)}).strict().parse(input);return database().transaction(async tx=>{
 const [prior]=await tx.select().from(supplierOrders).where(eq(supplierOrders.id,id)).for('update');if(!prior)throw new AppError(404,'NOT_FOUND','Supplier order not found.');if(prior.version!==data.version)throw new AppError(409,'VERSION_CONFLICT','Supplier order changed. Reload first.');
 if(!canTransition(supplierStatuses,prior.status,data.status))throw new AppError(422,'TRANSITION','Complete the preceding supplier stage first.');
 if(data.status==='Confirmed'&&(!prior.details.confirmationNumber||!prior.details.confirmationDate))throw new AppError(422,'CONFIRMATION_REQUIRED','Record the supplier confirmation number and date first.');
 if(data.status==='Received')throw new AppError(422,'RECEIVING_REQUIRED','Use goods receiving to update stock before marking received.');
 const [record]=await tx.update(supplierOrders).set({status:data.status,version:prior.version+1,updatedAt:new Date()}).where(eq(supplierOrders.id,id)).returning();if(data.status==='Confirmed'&&prior.orderId)await updateOrderProgress(tx,staff.id,prior.orderId,'supplier-confirmed',record.number,prior.supplierId);
 await tx.insert(auditLogs).values({userId:staff.id,entity:'supplier-order',entityId:id,action:'status-changed',before:{status:prior.status},after:{status:data.status}});return record;
});}
